facebook:
  client:
    clientId: 200297070914680
    clientSecret: 8d8a32c75668c03c5b24245f1aff79ad
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
google:
  client:
    clientId: 995526467465-c3bkfire4en068pc9441nbr1b8kvs7kb.apps.googleusercontent.com
    clientSecret: G7fHNnd0nni_ZacFBmHRH16D
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    preferTokenInfo: false

spring:
  main:
    allow-bean-definition-overriding: true

server:
  port: 8443
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-password: changeit
    key-store: classpath:ssl-server.jks
    key-store-provider: SUN
    key-store-type: JKS
